#!/sbin/busybox sh

echo "$int_scheduler" > /sys/block/mmcblk0/queue/scheduler
echo "$int_read_ahead_kb" > /sys/block/mmcblk0/queue/read_ahead_kb
echo "$ext_scheduler" > /sys/block/mmcblk0/mmcblk0rpmb/queue/scheduler
echo "$ext_read_ahead_kb" > /sys/block/mmcblk0/mmcblk0rpmb/queue/read_ahead_kb

echo "Scheduler settings applied"

